spring:
  application:
    name: board-service

  datasource:
    url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

server:
  port: 8082

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.practice.spring.boardservice.model

jwt:
  issuer: elec1001@gmail.com
  secret_key: 55DQ7XtZjKEuftetbQMtw0geU9SS1rR/fbrPOAqIQ2UUPJ+crjXRoLppDtreyvim53v3U6+hTLcbunHlxlNGlA==

